#!/bin/bash
### BEGIN INIT INFO
# Provides: revsw-cube 
# Required-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: revsw-cube service
# Description: This script starts / ends revsw-cube service.
### END INIT INFO

. /lib/lsb/init-functions

export PATH="$PATH:/usr/local/bin"
base_path="/opt/revsw-cube"
#forever="/opt/node-v0.10.24-linux-x64/bin/forever"

if [ -f /etc/default/revsw-cube ]; then
        . /etc/default/revsw-cube
fi

FOREVER=`which forever`

if [ -z "$FOREVER" ]; then
        echo "Error: 'forever' tool cannot be found - aborting"
        exit 1
fi

#Script created by Srikanth Thota

case "$1" in
        start)
                if [ ! -z "`forever list|egrep -e '(collector.js|evaluator.js)'`" ] ; then
                        log_action_msg "At least one component is already running..." || true
                        exit 1
                fi
                
		log_action_msg "Starting CUBE components (collector/evaluator)" || true
                cd $base_path

		forever start --append -o $base_path/log/collector.log bin/collector.js
		forever start --append -o $base_path/log/evaluator.log bin/evaluator.js

        ;;

        stop)

                log_daemon_msg "Stopping all CUBE services..." || true
                forever stop $base_path/bin/collector.js
                forever stop $base_path/bin/evaluator.js
        ;;
        restart)
                log_daemon_msg "Restarting all CUBE services..." || true
                $0 stop
                $0 start
        ;;
        status)
                forever list
                if [ ! -z "`forever list|egrep -e '(collector.js|evaluator.js)'`" ] ; then
                        log_action_msg "At least one component is already running..." || true
                        exit 1
                fi
        ;;
        *)
                log_action_msg "Usage: $0 {start|stop|restart|status}" || true
                exit 1
        ;;
esac
